palette = "catppuccin_macchiato"

# Disable the blank line at the start of the prompt
# add_newline = false

format = """
[](sky)\
$os\
$username\
[](bg:blue fg:sky)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green bg:surface1)\
$golang\
$java\
$nodejs\
[](fg:surface1 bg:mauve)\
$docker_context\
$kubernetes\
[](fg:mauve bg:blue)\
$time\
[ ](fg:lavender bg: blue)
 
"""

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green) ❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:sky fg:black"
style_root = "bg:sky fg:red"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:sky"
disabled = true # Disabled by default

[directory]
style = "bg:blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:mauve fg:black"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:green fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:surface1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue fg:black"
format = '[ ♥ $time ]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
style = "bg:mauve fg:black"


[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"


[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
